import { HomePage as MainPage_HomePage } from './MainPage/HomePage.component';
import { LoginScreen as LoginScreen_LoginScreen } from './LoginScreen/LoginScreen.component';
import { HomePage as Home_HomePage } from './Home/HomePage.component';
import { Default as Home_Default_Default } from './Home/Default/Default.component';
import { WarningmessageGrey as WarningmessageGrey_WarningmessageGrey } from './WarningmessageGrey/WarningmessageGrey.component';
import { WarningmessageRed as WarningmessageRed_WarningmessageRed } from './WarningmessageRed/WarningmessageRed.component';
import { PRODUCTIONCONTROLMENU as VMNUO002_ProdControl_PRODUCTIONCONTROLMENU } from './VMNUO002_ProdControl/PRODUCTIONCONTROLMENU.component';
import { MODELINFORMATIONCONTROLMENU as VMNUO002_ProdControl_MODELINFORMATIONCONTROLMENU_MODELINFORMATIONCONTROLMENU } from './VMNUO002_ProdControl/MODELINFORMATIONCONTROLMENU/MODELINFORMATIONCONTROLMENU.component';
import { PRODSCHEDULECONTROLMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODSCHEDULECONTROLMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/PRODSCHEDULECONTROLMENU.component';
import { MODELPLANMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_MODELPLANMENU_MODELPLANMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/MODELPLANMENU/MODELPLANMENU.component';
import { PRODUCTIONSEQUENCEPLANMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSEQUENCEPLANMENU_PRODUCTIONSEQUENCEPLANMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/PRODUCTIONSEQUENCEPLANMENU/PRODUCTIONSEQUENCEPLANMENU.component';
import { KDORDERPLANMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_KDORDERPLANMENU_KDORDERPLANMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/KDORDERPLANMENU/KDORDERPLANMENU.component';
import { ORDERPLANMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_ORDERPLANMENU_ORDERPLANMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/ORDERPLANMENU/ORDERPLANMENU.component';
import { PRODSCEDULECONTROLMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSCHEDULECONTMEN_PRODSCEDULECONTROLMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/PRODUCTIONSCHEDULECONTMEN/PRODSCEDULECONTROLMENU.component';
import { PRODUCTIONRESULTCONTROLMENU as VMNUO002_ProdControl_PRODUCTIONRESULTCONTROLMENU_PRODUCTIONRESULTCONTROLMENU } from './VMNUO002_ProdControl/PRODUCTIONRESULTCONTROLMENU/PRODUCTIONRESULTCONTROLMENU.component';
import { PRODUCTIONRESULTENTRYMENU as VMNUO002_ProdControl_PRODRESULTENTRYMENUHMS_PRODUCTIONRESULTENTRYMENU } from './VMNUO002_ProdControl/PRODRESULTENTRYMENUHMS/PRODUCTIONRESULTENTRYMENU.component';
import { MENUSELECT as VMNUO002_ProdControl_MENUSELECT_MENUSELECT } from './VMNUO002_ProdControl/MENUSELECT/MENUSELECT.component';
import { GENERALMENU as VMNUO001_GENERAL_MENU_GENERALMENU } from './VMNUO001_GENERAL_MENU/GENERALMENU.component';
import { FactoryConfirmation as VMNUO001_GENERAL_MENU_FactoryConfirmation_FactoryConfirmation } from './VMNUO001_GENERAL_MENU/FactoryConfirmation/FactoryConfirmation.component';
import { AEOFF_RESULT_ENTRY as VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY } from './VPRDO041DISPAE_OFF_ENTRY/AEOFF_RESULT_ENTRY.component';
import { AEOFF_RESULT_ENTRY as VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY } from './VPRDO041DISPAE_OFF_ENTRY/AEOFFRESULTENTRY/AEOFF_RESULT_ENTRY.component';
import { AE_OFF_RESULT_ENTRY2 as VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2 } from './VPRDO041DISPAE_OFF_ENTRY/AEOFFRESULTENTRY/AEOFF_RESULT_ENTRY2/AE_OFF_RESULT_ENTRY2.component';
import { AEOFF_RESULT_ENTRY_HMSI as VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY_HMSI } from './VPRDO041DISPAE_OFF_ENTRY/AEOFF_RESULT_ENTRY_HMSI/AEOFF_RESULT_ENTRY_HMSI.component';
import { AEOFF_RESULT_ENTRY2 as VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY2_AEOFF_RESULT_ENTRY2 } from './VPRDO041DISPAE_OFF_ENTRY/AEOFF_RESULT_ENTRY_HMSI/AEOFF_RESULT_ENTRY2/AEOFF_RESULT_ENTRY2.component';
import { ERROR_MESSAGE as VPRDO041DISPAE_OFF_ENTRY_ERROR_MESSAGE_ERROR_MESSAGE } from './VPRDO041DISPAE_OFF_ENTRY/ERROR_MESSAGE/ERROR_MESSAGE.component';
import { AEOFFRESULTENTRY as VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AEOFFRESULTENTRY } from './VPRDO041DISPAE_OFF_ENTRY/AEOFF_RESULT_ENTRY_HMSI2/AEOFFRESULTENTRY.component';
import { AE_OFF_RESULT_ENTRY2 as VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AE_OFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2 } from './VPRDO041DISPAE_OFF_ENTRY/AEOFF_RESULT_ENTRY_HMSI2/AE_OFF_RESULT_ENTRY2/AE_OFF_RESULT_ENTRY2.component';
import { MESSAGE as VPRDO041DISPAE_OFF_ENTRY_CONFIRMATION_MESSAGE_MESSAGE } from './VPRDO041DISPAE_OFF_ENTRY/CONFIRMATION_MESSAGE/MESSAGE.component';
import { VPRDS004PrintingConfir as VPRDS004PrintingConfir_VPRDS004PrintingConfir } from './VPRDS004PrintingConfir/VPRDS004PrintingConfir.component';
import { VPRDS005OKNO as VPRDS005OKNO_VPRDS005OKNO } from './VPRDS005OKNO/VPRDS005OKNO.component';
import { VPRDS012WARNING as VPRDS012WARNING_VPRDS012WARNING } from './VPRDS012WARNING/VPRDS012WARNING.component';
import { PRDS024 as VPRDS024_PRDS024 } from './VPRDS024/PRDS024.component';
import { ATVCOUPONPRINT as VSHPO035ORATVCoupon_ATVCOUPONPRINT } from './VSHPO035ORATVCoupon/ATVCOUPONPRINT.component';
import { CHASSISNOGUIDE as VPRDG003PRD003_GUIDE_CHASSISNOGUIDE } from './VPRDG003PRD003_GUIDE/CHASSISNOGUIDE.component';
import { VPRDB005LTRUEISSUEPRO as VPRDB005_LPRDINDICATELIST_VPRDB005LTRUEISSUEPRO } from './VPRDB005_LPRDINDICATELIST/VPRDB005LTRUEISSUEPRO.component';
import { VPRDS002PrintConfirmOkonly as VPRDS002PrintConfirmOkonly_VPRDS002PrintConfirmOkonly } from './VPRDS002PrintConfirmOkonly/VPRDS002PrintConfirmOkonly.component';
import { VPRDB004ORKANKENSYOHSC as VPRDB004ORFVISPRINTHSC_VPRDB004ORKANKENSYOHSC } from './VPRDB004ORFVISPRINTHSC/VPRDB004ORKANKENSYOHSC.component';
import { VPRDB066RTRUEISSUEPRO as VPRDB066_RFIVSPRINTHMSI_VPRDB066RTRUEISSUEPRO } from './VPRDB066_RFIVSPRINTHMSI/VPRDB066RTRUEISSUEPRO.component';
import { VPRDB052ENGFRMBARCDLABEL as VPRDB052PEBARCDPRINTPE_VPRDB052ENGFRMBARCDLABEL } from './VPRDB052PEBARCDPRINTPE/VPRDB052ENGFRMBARCDLABEL.component';
import { VPRDB062HPEFIVSPRINT as VPRDB062FIVSPRINTHPE_VPRDB062HPEFIVSPRINT } from './VPRDB062FIVSPRINTHPE/VPRDB062HPEFIVSPRINT.component';
import { VPRDB007RTRUEISSUEPRO as VPRDB007_RENGPRINTHVNetc_VPRDB007RTRUEISSUEPRO } from './VPRDB007_RENGPRINTHVNetc/VPRDB007RTRUEISSUEPRO.component';
import { VPRDB034ENGINECARDISSUE as VPRDB034ENGPRINTHSC_VPRDB034ENGINECARDISSUE } from './VPRDB034ENGPRINTHSC/VPRDB034ENGINECARDISSUE.component';
import { VPRDB040STAMPINGMASTERINFO as VPRDB040STAMPINGMASTERINFO_VPRDB040STAMPINGMASTERINFO } from './VPRDB040STAMPINGMASTERINFO/VPRDB040STAMPINGMASTERINFO.component';
import { VPRDB008LTRUEISSUEPRO as VPRDB008_LFRAMESEALPRINT_VPRDB008LTRUEISSUEPRO } from './VPRDB008_LFRAMESEALPRINT/VPRDB008LTRUEISSUEPRO.component';

export const title = "";

export const magicGenCmpsHash = {               VPRDS004PrintingConfir_VPRDS004PrintingConfir:VPRDS004PrintingConfir_VPRDS004PrintingConfir,
              VPRDS005OKNO_VPRDS005OKNO:VPRDS005OKNO_VPRDS005OKNO,
              VPRDS012WARNING_VPRDS012WARNING:VPRDS012WARNING_VPRDS012WARNING,
              VPRDS024_PRDS024:VPRDS024_PRDS024,
              VSHPO035ORATVCoupon_ATVCOUPONPRINT:VSHPO035ORATVCoupon_ATVCOUPONPRINT,
              VPRDG003PRD003_GUIDE_CHASSISNOGUIDE:VPRDG003PRD003_GUIDE_CHASSISNOGUIDE,
              VPRDB005_LPRDINDICATELIST_VPRDB005LTRUEISSUEPRO:VPRDB005_LPRDINDICATELIST_VPRDB005LTRUEISSUEPRO,
              VPRDS002PrintConfirmOkonly_VPRDS002PrintConfirmOkonly:VPRDS002PrintConfirmOkonly_VPRDS002PrintConfirmOkonly,
              VPRDB004ORFVISPRINTHSC_VPRDB004ORKANKENSYOHSC:VPRDB004ORFVISPRINTHSC_VPRDB004ORKANKENSYOHSC,
              VPRDB066_RFIVSPRINTHMSI_VPRDB066RTRUEISSUEPRO:VPRDB066_RFIVSPRINTHMSI_VPRDB066RTRUEISSUEPRO,
              VPRDB052PEBARCDPRINTPE_VPRDB052ENGFRMBARCDLABEL:VPRDB052PEBARCDPRINTPE_VPRDB052ENGFRMBARCDLABEL,
              VPRDB062FIVSPRINTHPE_VPRDB062HPEFIVSPRINT:VPRDB062FIVSPRINTHPE_VPRDB062HPEFIVSPRINT,
              VPRDB007_RENGPRINTHVNetc_VPRDB007RTRUEISSUEPRO:VPRDB007_RENGPRINTHVNetc_VPRDB007RTRUEISSUEPRO,
              VPRDB034ENGPRINTHSC_VPRDB034ENGINECARDISSUE:VPRDB034ENGPRINTHSC_VPRDB034ENGINECARDISSUE,
              VPRDB040STAMPINGMASTERINFO_VPRDB040STAMPINGMASTERINFO:VPRDB040STAMPINGMASTERINFO_VPRDB040STAMPINGMASTERINFO,
              VPRDB008_LFRAMESEALPRINT_VPRDB008LTRUEISSUEPRO:VPRDB008_LFRAMESEALPRINT_VPRDB008LTRUEISSUEPRO,
                      VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY:VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY,
              VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY:VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY,
              VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2:VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2,
              VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY_HMSI:VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY_HMSI,
              VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY2_AEOFF_RESULT_ENTRY2:VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY2_AEOFF_RESULT_ENTRY2,
              VPRDO041DISPAE_OFF_ENTRY_ERROR_MESSAGE_ERROR_MESSAGE:VPRDO041DISPAE_OFF_ENTRY_ERROR_MESSAGE_ERROR_MESSAGE,
              VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AEOFFRESULTENTRY:VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AEOFFRESULTENTRY,
              VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AE_OFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2:VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AE_OFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2,
              VPRDO041DISPAE_OFF_ENTRY_CONFIRMATION_MESSAGE_MESSAGE:VPRDO041DISPAE_OFF_ENTRY_CONFIRMATION_MESSAGE_MESSAGE,
                      VMNUO001_GENERAL_MENU_GENERALMENU:VMNUO001_GENERAL_MENU_GENERALMENU,
              VMNUO001_GENERAL_MENU_FactoryConfirmation_FactoryConfirmation:VMNUO001_GENERAL_MENU_FactoryConfirmation_FactoryConfirmation,
                      VMNUO002_ProdControl_PRODUCTIONCONTROLMENU:VMNUO002_ProdControl_PRODUCTIONCONTROLMENU,
              VMNUO002_ProdControl_MODELINFORMATIONCONTROLMENU_MODELINFORMATIONCONTROLMENU:VMNUO002_ProdControl_MODELINFORMATIONCONTROLMENU_MODELINFORMATIONCONTROLMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODSCHEDULECONTROLMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODSCHEDULECONTROLMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_MODELPLANMENU_MODELPLANMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_MODELPLANMENU_MODELPLANMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSEQUENCEPLANMENU_PRODUCTIONSEQUENCEPLANMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSEQUENCEPLANMENU_PRODUCTIONSEQUENCEPLANMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_KDORDERPLANMENU_KDORDERPLANMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_KDORDERPLANMENU_KDORDERPLANMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_ORDERPLANMENU_ORDERPLANMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_ORDERPLANMENU_ORDERPLANMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSCHEDULECONTMEN_PRODSCEDULECONTROLMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSCHEDULECONTMEN_PRODSCEDULECONTROLMENU,
              VMNUO002_ProdControl_PRODUCTIONRESULTCONTROLMENU_PRODUCTIONRESULTCONTROLMENU:VMNUO002_ProdControl_PRODUCTIONRESULTCONTROLMENU_PRODUCTIONRESULTCONTROLMENU,
              VMNUO002_ProdControl_PRODRESULTENTRYMENUHMS_PRODUCTIONRESULTENTRYMENU:VMNUO002_ProdControl_PRODRESULTENTRYMENUHMS_PRODUCTIONRESULTENTRYMENU,
              VMNUO002_ProdControl_MENUSELECT_MENUSELECT:VMNUO002_ProdControl_MENUSELECT_MENUSELECT,
                      WarningmessageGrey_WarningmessageGrey:WarningmessageGrey_WarningmessageGrey,
              WarningmessageRed_WarningmessageRed:WarningmessageRed_WarningmessageRed,
                      MainPage_HomePage:MainPage_HomePage,
              LoginScreen_LoginScreen:LoginScreen_LoginScreen,
              Home_HomePage:Home_HomePage,
              Home_Default_Default:Home_Default_Default,
       
};

export const magicGenComponents = [
	VPRDS004PrintingConfir_VPRDS004PrintingConfir,
	VPRDS005OKNO_VPRDS005OKNO,
	VPRDS012WARNING_VPRDS012WARNING,
	VPRDS024_PRDS024,
	VSHPO035ORATVCoupon_ATVCOUPONPRINT,
	VPRDG003PRD003_GUIDE_CHASSISNOGUIDE,
	VPRDB005_LPRDINDICATELIST_VPRDB005LTRUEISSUEPRO,
	VPRDS002PrintConfirmOkonly_VPRDS002PrintConfirmOkonly,
	VPRDB004ORFVISPRINTHSC_VPRDB004ORKANKENSYOHSC,
	VPRDB066_RFIVSPRINTHMSI_VPRDB066RTRUEISSUEPRO,
	VPRDB052PEBARCDPRINTPE_VPRDB052ENGFRMBARCDLABEL,
	VPRDB062FIVSPRINTHPE_VPRDB062HPEFIVSPRINT,
	VPRDB007_RENGPRINTHVNetc_VPRDB007RTRUEISSUEPRO,
	VPRDB034ENGPRINTHSC_VPRDB034ENGINECARDISSUE,
	VPRDB040STAMPINGMASTERINFO_VPRDB040STAMPINGMASTERINFO,
	VPRDB008_LFRAMESEALPRINT_VPRDB008LTRUEISSUEPRO,
	VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY,
	VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY,
	VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2,
	VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY_HMSI,
	VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY2_AEOFF_RESULT_ENTRY2,
	VPRDO041DISPAE_OFF_ENTRY_ERROR_MESSAGE_ERROR_MESSAGE,
	VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AEOFFRESULTENTRY,
	VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AE_OFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2,
	VPRDO041DISPAE_OFF_ENTRY_CONFIRMATION_MESSAGE_MESSAGE,
	VMNUO001_GENERAL_MENU_GENERALMENU,
	VMNUO001_GENERAL_MENU_FactoryConfirmation_FactoryConfirmation,
	VMNUO002_ProdControl_PRODUCTIONCONTROLMENU,
	VMNUO002_ProdControl_MODELINFORMATIONCONTROLMENU_MODELINFORMATIONCONTROLMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODSCHEDULECONTROLMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_MODELPLANMENU_MODELPLANMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSEQUENCEPLANMENU_PRODUCTIONSEQUENCEPLANMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_KDORDERPLANMENU_KDORDERPLANMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_ORDERPLANMENU_ORDERPLANMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSCHEDULECONTMEN_PRODSCEDULECONTROLMENU,
	VMNUO002_ProdControl_PRODUCTIONRESULTCONTROLMENU_PRODUCTIONRESULTCONTROLMENU,
	VMNUO002_ProdControl_PRODRESULTENTRYMENUHMS_PRODUCTIONRESULTENTRYMENU,
	VMNUO002_ProdControl_MENUSELECT_MENUSELECT,
	WarningmessageGrey_WarningmessageGrey,
	WarningmessageRed_WarningmessageRed,
	MainPage_HomePage,
	LoginScreen_LoginScreen,
	Home_HomePage,
	Home_Default_Default 
];


export const LazyLoadModulesMap = {};