import { HomePage as MainPage_HomePage } from './MainPage/HomePage.component';
import { LoginScreen as LoginScreen_LoginScreen } from './LoginScreen/LoginScreen.component';
import { HomePage as Home_HomePage } from './Home/HomePage.component';
import { Default as Home_Default_Default } from './Home/Default/Default.component';
import { WarningmessageGrey as WarningmessageGrey_WarningmessageGrey } from './WarningmessageGrey/WarningmessageGrey.component';
import { WarningmessageRed as WarningmessageRed_WarningmessageRed } from './WarningmessageRed/WarningmessageRed.component';
import { PRODUCTIONCONTROLMENU as VMNUO002_ProdControl_PRODUCTIONCONTROLMENU } from './VMNUO002_ProdControl/PRODUCTIONCONTROLMENU.component';
import { MODELINFORMATIONCONTROLMENU as VMNUO002_ProdControl_MODELINFORMATIONCONTROLMENU_MODELINFORMATIONCONTROLMENU } from './VMNUO002_ProdControl/MODELINFORMATIONCONTROLMENU/MODELINFORMATIONCONTROLMENU.component';
import { PRODSCHEDULECONTROLMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODSCHEDULECONTROLMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/PRODSCHEDULECONTROLMENU.component';
import { MODELPLANMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_MODELPLANMENU_MODELPLANMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/MODELPLANMENU/MODELPLANMENU.component';
import { PRODUCTIONSEQUENCEPLANMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSEQUENCEPLANMENU_PRODUCTIONSEQUENCEPLANMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/PRODUCTIONSEQUENCEPLANMENU/PRODUCTIONSEQUENCEPLANMENU.component';
import { KDORDERPLANMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_KDORDERPLANMENU_KDORDERPLANMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/KDORDERPLANMENU/KDORDERPLANMENU.component';
import { ORDERPLANMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_ORDERPLANMENU_ORDERPLANMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/ORDERPLANMENU/ORDERPLANMENU.component';
import { PRODSCEDULECONTROLMENU as VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSCHEDULECONTMEN_PRODSCEDULECONTROLMENU } from './VMNUO002_ProdControl/PRODUCTIONSCHEDULECONTMEN/PRODUCTIONSCHEDULECONTMEN/PRODSCEDULECONTROLMENU.component';
import { PRODUCTIONRESULTCONTROLMENU as VMNUO002_ProdControl_PRODUCTIONRESULTCONTROLMENU_PRODUCTIONRESULTCONTROLMENU } from './VMNUO002_ProdControl/PRODUCTIONRESULTCONTROLMENU/PRODUCTIONRESULTCONTROLMENU.component';
import { PRODUCTIONRESULTENTRYMENU as VMNUO002_ProdControl_PRODRESULTENTRYMENUHMS_PRODUCTIONRESULTENTRYMENU } from './VMNUO002_ProdControl/PRODRESULTENTRYMENUHMS/PRODUCTIONRESULTENTRYMENU.component';
import { MENUSELECT as VMNUO002_ProdControl_MENUSELECT_MENUSELECT } from './VMNUO002_ProdControl/MENUSELECT/MENUSELECT.component';
import { GENERALMENU as VMNUO001_GENERAL_MENU_GENERALMENU } from './VMNUO001_GENERAL_MENU/GENERALMENU.component';
import { FactoryConfirmation as VMNUO001_GENERAL_MENU_FactoryConfirmation_FactoryConfirmation } from './VMNUO001_GENERAL_MENU/FactoryConfirmation/FactoryConfirmation.component';
import { AEOFF_RESULT_ENTRY as VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY } from './VPRDO041DISPAE_OFF_ENTRY/AEOFF_RESULT_ENTRY.component';
import { AEOFF_RESULT_ENTRY as VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY } from './VPRDO041DISPAE_OFF_ENTRY/AEOFFRESULTENTRY/AEOFF_RESULT_ENTRY.component';
import { AE_OFF_RESULT_ENTRY2 as VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2 } from './VPRDO041DISPAE_OFF_ENTRY/AEOFFRESULTENTRY/AEOFF_RESULT_ENTRY2/AE_OFF_RESULT_ENTRY2.component';
import { AEOFF_RESULT_ENTRY_HMSI as VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY_HMSI } from './VPRDO041DISPAE_OFF_ENTRY/AEOFF_RESULT_ENTRY_HMSI/AEOFF_RESULT_ENTRY_HMSI.component';
import { AEOFF_RESULT_ENTRY2 as VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY2_AEOFF_RESULT_ENTRY2 } from './VPRDO041DISPAE_OFF_ENTRY/AEOFF_RESULT_ENTRY_HMSI/AEOFF_RESULT_ENTRY2/AEOFF_RESULT_ENTRY2.component';
import { ERROR_MESSAGE as VPRDO041DISPAE_OFF_ENTRY_ERROR_MESSAGE_ERROR_MESSAGE } from './VPRDO041DISPAE_OFF_ENTRY/ERROR_MESSAGE/ERROR_MESSAGE.component';
import { AEOFFRESULTENTRY as VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AEOFFRESULTENTRY } from './VPRDO041DISPAE_OFF_ENTRY/AEOFF_RESULT_ENTRY_HMSI2/AEOFFRESULTENTRY.component';
import { AE_OFF_RESULT_ENTRY2 as VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AE_OFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2 } from './VPRDO041DISPAE_OFF_ENTRY/AEOFF_RESULT_ENTRY_HMSI2/AE_OFF_RESULT_ENTRY2/AE_OFF_RESULT_ENTRY2.component';
import { MESSAGE as VPRDO041DISPAE_OFF_ENTRY_CONFIRMATION_MESSAGE_MESSAGE } from './VPRDO041DISPAE_OFF_ENTRY/CONFIRMATION_MESSAGE/MESSAGE.component';

export const title = "";

export const magicGenCmpsHash = {               VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY:VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY,
              VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY:VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY,
              VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2:VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2,
              VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY_HMSI:VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY_HMSI,
              VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY2_AEOFF_RESULT_ENTRY2:VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY2_AEOFF_RESULT_ENTRY2,
              VPRDO041DISPAE_OFF_ENTRY_ERROR_MESSAGE_ERROR_MESSAGE:VPRDO041DISPAE_OFF_ENTRY_ERROR_MESSAGE_ERROR_MESSAGE,
              VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AEOFFRESULTENTRY:VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AEOFFRESULTENTRY,
              VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AE_OFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2:VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AE_OFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2,
              VPRDO041DISPAE_OFF_ENTRY_CONFIRMATION_MESSAGE_MESSAGE:VPRDO041DISPAE_OFF_ENTRY_CONFIRMATION_MESSAGE_MESSAGE,
                      VMNUO001_GENERAL_MENU_GENERALMENU:VMNUO001_GENERAL_MENU_GENERALMENU,
              VMNUO001_GENERAL_MENU_FactoryConfirmation_FactoryConfirmation:VMNUO001_GENERAL_MENU_FactoryConfirmation_FactoryConfirmation,
                      VMNUO002_ProdControl_PRODUCTIONCONTROLMENU:VMNUO002_ProdControl_PRODUCTIONCONTROLMENU,
              VMNUO002_ProdControl_MODELINFORMATIONCONTROLMENU_MODELINFORMATIONCONTROLMENU:VMNUO002_ProdControl_MODELINFORMATIONCONTROLMENU_MODELINFORMATIONCONTROLMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODSCHEDULECONTROLMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODSCHEDULECONTROLMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_MODELPLANMENU_MODELPLANMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_MODELPLANMENU_MODELPLANMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSEQUENCEPLANMENU_PRODUCTIONSEQUENCEPLANMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSEQUENCEPLANMENU_PRODUCTIONSEQUENCEPLANMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_KDORDERPLANMENU_KDORDERPLANMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_KDORDERPLANMENU_KDORDERPLANMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_ORDERPLANMENU_ORDERPLANMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_ORDERPLANMENU_ORDERPLANMENU,
              VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSCHEDULECONTMEN_PRODSCEDULECONTROLMENU:VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSCHEDULECONTMEN_PRODSCEDULECONTROLMENU,
              VMNUO002_ProdControl_PRODUCTIONRESULTCONTROLMENU_PRODUCTIONRESULTCONTROLMENU:VMNUO002_ProdControl_PRODUCTIONRESULTCONTROLMENU_PRODUCTIONRESULTCONTROLMENU,
              VMNUO002_ProdControl_PRODRESULTENTRYMENUHMS_PRODUCTIONRESULTENTRYMENU:VMNUO002_ProdControl_PRODRESULTENTRYMENUHMS_PRODUCTIONRESULTENTRYMENU,
              VMNUO002_ProdControl_MENUSELECT_MENUSELECT:VMNUO002_ProdControl_MENUSELECT_MENUSELECT,
                      WarningmessageGrey_WarningmessageGrey:WarningmessageGrey_WarningmessageGrey,
              WarningmessageRed_WarningmessageRed:WarningmessageRed_WarningmessageRed,
                      MainPage_HomePage:MainPage_HomePage,
              LoginScreen_LoginScreen:LoginScreen_LoginScreen,
              Home_HomePage:Home_HomePage,
              Home_Default_Default:Home_Default_Default,
       
};

export const magicGenComponents = [
	VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY,
	VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY,
	VPRDO041DISPAE_OFF_ENTRY_AEOFFRESULTENTRY_AEOFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2,
	VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY_HMSI,
	VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI_AEOFF_RESULT_ENTRY2_AEOFF_RESULT_ENTRY2,
	VPRDO041DISPAE_OFF_ENTRY_ERROR_MESSAGE_ERROR_MESSAGE,
	VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AEOFFRESULTENTRY,
	VPRDO041DISPAE_OFF_ENTRY_AEOFF_RESULT_ENTRY_HMSI2_AE_OFF_RESULT_ENTRY2_AE_OFF_RESULT_ENTRY2,
	VPRDO041DISPAE_OFF_ENTRY_CONFIRMATION_MESSAGE_MESSAGE,
	VMNUO001_GENERAL_MENU_GENERALMENU,
	VMNUO001_GENERAL_MENU_FactoryConfirmation_FactoryConfirmation,
	VMNUO002_ProdControl_PRODUCTIONCONTROLMENU,
	VMNUO002_ProdControl_MODELINFORMATIONCONTROLMENU_MODELINFORMATIONCONTROLMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODSCHEDULECONTROLMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_MODELPLANMENU_MODELPLANMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSEQUENCEPLANMENU_PRODUCTIONSEQUENCEPLANMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_KDORDERPLANMENU_KDORDERPLANMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_ORDERPLANMENU_ORDERPLANMENU,
	VMNUO002_ProdControl_PRODUCTIONSCHEDULECONTMEN_PRODUCTIONSCHEDULECONTMEN_PRODSCEDULECONTROLMENU,
	VMNUO002_ProdControl_PRODUCTIONRESULTCONTROLMENU_PRODUCTIONRESULTCONTROLMENU,
	VMNUO002_ProdControl_PRODRESULTENTRYMENUHMS_PRODUCTIONRESULTENTRYMENU,
	VMNUO002_ProdControl_MENUSELECT_MENUSELECT,
	WarningmessageGrey_WarningmessageGrey,
	WarningmessageRed_WarningmessageRed,
	MainPage_HomePage,
	LoginScreen_LoginScreen,
	Home_HomePage,
	Home_Default_Default 
];


export const LazyLoadModulesMap = {};